"""
Django settings for django_pyjwt_example project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q)388tj%rb_m_(q8$r_e+k$+k_o&#11jwnxofoo@sd(3l)i^$d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_pyjwt_example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_pyjwt_example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'django_pyjwt_example.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions'
    ]
}

JWT_PUBLIC_KEY = """
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA63h1q2ph8PtxjxETS1gT
1ffP4ae6gE/FtWnPD0IEbCG7RS4qBA7E8TU+fv4dLFmTUK4SL8GNeebOo9UkRg+5
8FZFlAnhgJFJ/zK17XvNrK8rSxa5ikUiu4Kcl9CDt+vQ8LAAhaMUNTlOmwhQYO2h
/mEf8uR2bi9xZiJAmIfN6sjt/ali59h581sL2HhIQ7DLimXR191Xu8fJ5nXp8YAj
kTNOGvdBAeFq0f7j9ZXTWdGB31UMOH9Yhmgi/xOCLCUtbsw0UbShaFDo3/i1zgtw
333wW1M2chRMIHlORDOh9piVfKYC22WaPbOZLMfMcNcgmJ+W8NYMAh9q3VLavzcO
HDQxvQU0zoItbkDHmaldHio5N4qQH1Z94xbEve87dLg7W5QEfqMSF8QXvlB0lp/Y
f4WgHlV4Y0Grb6FfG/g1zfNvE+UoewexcFIUeGTZ7lAuPYmtSGWBXAuxIN7phHyK
LNF7InpuIAf6kJ1deqGRGzq6UOB9gGQiDtkv/ep98du6c2iXWGmsTcoT5C7DNkDb
GIJZLEYWULn1mQKbk2dWTR7aEZRgTRjkbSoGpHyZpOl8hCYq8NRSQu5wjIvwwxJy
iqPWMkFG2/mCBzDhinWWPmIQwOcTjMnt98ahbHGX3/wMqfVoCe09DBUXYXIpP0KL
Ge2oLhjxoggTe3jh1K9Id5MCAwEAAQ==
-----END PUBLIC KEY-----
"""


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
